apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  holdInstallation: true
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.6.82.0/24
    serviceNetwork:
      - 172.30.0.0/16
    userManagedNetworking: true
  provisionRequirements:
    controlPlaneAgents: 1
  imageSetRef:
    #quay.io/openshift-release-dev/ocp-release:4.12.30-multi
    name: img{{ .Values.cluster.version }}-multi-appsub   

