apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
  labels:
    cluster.open-cluster-management.io/clusterset: default
    hive.openshift.io/cluster-platform: agent-baremetal      
spec:
  baseDomain: redhat.hpecic.net
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{ .Values.cluster.name }}
    version: v1beta1
  clusterName: {{ .Values.cluster.name }}
  controlPlaneConfig:
    servingCertificates: {} 
  installed: false
  platform:
    agentBareMetal:
      agentSelector: {}
  pullSecretRef:
    name: {{ .Values.cluster.name }}-template-merged-pull-secret