kind: ConfigMap
apiVersion: v1
metadata:
  name: 98-var-partition
  namespace: {{ .Values.cluster.namespace }}
data:
  98-var-partition.yaml : |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: master
      name: 98-var-partition
    spec:
      config:
        ignition:
          version: 3.4.0
        storage:
          disks:
            - device: /dev/sda
              partitions:
                - label: lvmstorage
                  number: 4
                  sizeMiB: 0
                  startMiB: 25217
