apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"    
---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.cluster.name }}-template
  namespace: {{ .Values.cluster.namespace }}
  labels:
    cluster.open-cluster-management.io/clusterset: default
    hive.openshift.io/cluster-platform: agent-baremetal  
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"      
spec:
  baseDomain: redhat.hpecic.net
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{ .Values.cluster.name }}-template
    version: v1beta1
  clusterName: {{ .Values.cluster.name }}
  controlPlaneConfig:
    servingCertificates: {} 
  installed: false
  platform:
    agentBareMetal:
      agentSelector: {}
---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{ .Values.cluster.name }}-template
  namespace: {{ .Values.cluster.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"    
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}-template
  holdInstallation: true
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 10.6.82.0/24
    serviceNetwork:
      - 172.30.0.0/16
    userManagedNetworking: true
  provisionRequirements:
    controlPlaneAgents: 1
  imageSetRef:
    #quay.io/openshift-release-dev/ocp-release:4.12.30-multi
    name: img{{ .Values.cluster.version }}-multi-appsub         