apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno-@name@
  labels:
    cloud: BareMetal
    cluster.open-cluster-management.io/clusterset: default
    feature.open-cluster-management.io/addon-application-manager: unreachable
    feature.open-cluster-management.io/addon-cert-policy-controller: unreachable
    feature.open-cluster-management.io/addon-cluster-proxy: unreachable
    feature.open-cluster-management.io/addon-iam-policy-controller: unreachable
    feature.open-cluster-management.io/addon-search-collector: unreachable
    feature.open-cluster-management.io/addon-work-manager: unreachable
    name: sno-@name@
    vendor: OpenShift
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
  taints:
    - effect: NoSelect
      key: cluster.open-cluster-management.io/unreachable
      timeAdded: '2024-04-11T06:57:53Z'
